{{- if .Values.postInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rancher.fullname" . }}-post-install
  namespace: {{ .Release.Namespace }}
  labels: {{ include "rancher.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ template "rancher.fullname" . }}-post-install
      labels: {{ include "rancher.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "rancher.fullname" . }}-post-install
      restartPolicy: OnFailure
      containers:
        - name: {{ template "rancher.name" . }}-post-install
          image: "{{ include "system_default_registry" . }}{{ .Values.postInstall.image.repository }}:{{ .Values.postInstall.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - /scripts/post-install-hook.sh
          volumeMounts:
            - mountPath: /scripts
              name: config-volume
          env:
            - name: TIMEOUT
              value: {{ .Values.postInstall.timeout | quote }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "rancher.fullname" . }}-post-install
            defaultMode: 0777
{{- end }}
